config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root 'home#index'
  get 'about', to: 'pages#about'
  resources :courses do
    get :search, on: :collection
  end
  resources :students, only: %i[index show]
  resources :student_courses, only: %i[index create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings do
    mappings dynamic: false do
      indexes :short_name, type: :text, analyzer: :english
      indexes :name, type: :text, analyzer: :english
      indexes :description, type: :text, analyzer: :english
    end
  end

  validates :short_name, :name, :description, presence: true
  validates :short_name, :name, uniqueness: { case_sensitive: false }

  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :first_name, :last_name, presence: true

  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:first_name, :last_name, :email, :password, :current_password)
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_student!

  def index
    render :index, locals: { courses: Course.all }
  end

  def show

  end

  def new

  end

  def search
    render :search, locals: { courses: Course.search(params[:query]) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController

  def index
    render :index, locals: { student_courses: StudentCourse.where(student: current_student) }
  end

  def create
    student = Student.find(params.dig(:student_course, :student))
    course = Course.find(params.dig(:student_course, :course))
    student_course = StudentCourse.new(student: student, course: course)

    if student_course.save
      redirect_to student_courses_path, notice: 'You have successfully enrolled in the course.'
    else
      redirect_to courses_path, alert: 'An error has occurred.'
    end
  end

  def destroy
    student_course.destroy

    redirect_to student_courses_path, notice: 'You have successfully signed off the course.'
  end

  private

  def student_course
    @student_course ||= StudentCourse.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def index
    render :index, locals: { students: Student.all}
  end

  def show
    render :show, locals: { student: student }
  end

  private

  def student
    @student ||= Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<h1 class='text-center mt-5'>Course Listing</h1>
<%= link_to 'Search Courses', search_courses_path, class: 'btn btn-primary'%>

<div class="container mt-5">
  <div class="row">
    <% courses.each do |course| %>
      <div class="col-sm-4">
        <div class="card mb-5">
          <div class="card-body">
            <h5 class="card-title"><%= course.short_name %>: <%= course.name %></h5>
            <p class="card-text"><%= course.description %></p>
            <hr class='divider'>
            <%= button_to 'Enroll', student_courses_path(student_course: { student: current_student, course: course }), method: :post, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'btn btn-success' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/search.html.erb
<h1 class='text-center mb-5 mt-5'>Search Courses</h1>

<%= form_with url: search_courses_path, method: :get do |form| %>
 <div class="row">
  <div class="col-10">
      <%= form.text_field :query, class: 'form-control me-2', type: 'search', placeholder: 'Search', aria_label: 'Search' %>
    </div>
    <div class="col-2">
        <%= form.submit 'Search', class: 'btn btn-outline-success', type: 'submit' %>
    </div>
  </div>
<% end %>

<% unless courses.nil? %>
  <% if courses.empty? %>
    <h2 class='text-center mt-5'>No courses found matching your query.</h2>
  <% else %>
    <div class="container mt-5">
      <div class="row">
        <% courses.each do |course| %>
          <div class="col-sm-4">
            <div class="card mb-5">
              <div class="card-body">
                <h5 class="card-title"><%= course.short_name %>: <%= course.name %></h5>
                <p class="card-text"><%= course.description %></p>
                <hr class='divider'>
                <%= button_to 'Enroll', student_courses_path(student_course: { student: current_student, course: course }), method: :post, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'btn btn-success' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/home/index.html.erb
Welcome :)

app/views/layouts/_footer.html.erb
<div class="text-center p-3" style="background-color: rgba(72 122 180 / .2);">
  © 2020 Copyright:
  <a class="text-dark" href="#">iAcay</a>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
    <%= notice.html_safe %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
    <%= alert.html_safe %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md" style="background-color: rgba(72 122 180 / .2);">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="collapseNavbar">
      <ul class="navbar-nav">
        <li class="nav-item active"><%= link_to 'About', about_path, class: 'nav-link' %></li>
        <li class='navbar-nav'><%= link_to 'Courses', courses_path, class: 'nav-link' %></li>
        <li class='navbar-nav'><%= link_to 'Your Courses', student_courses_path, class: 'nav-link' %></li>
        <li class='navbar-nav'><%= link_to 'Students', students_path, class: 'nav-link' %></li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_student %>
          <li class="nav-item dropstart">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Account', edit_student_registration_path, class: 'dropdown-item' %></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <%= button_to "Log out", destroy_student_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'Sign Up', new_student_registration_path, class: 'nav-link' %>
          <%= link_to 'Sign In', new_student_session_path, class: 'nav-link' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppForUniversities</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main>
      <div class="container mt-3">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
    <footer class="page-footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
About

app/views/student_courses/index.html.erb
<h1 class='text-center mt-5'>Your courses</h1>

<div class="container mt-5">
  <div class="row">
    <% student_courses.each do |student_course| %>
      <div class="col-sm-4">
        <div class="card mb-5">
          <div class="card-body">
            <h5 class="card-title"><%= student_course.course.short_name %>: <%= student_course.course.name %></h5>
            <p class="card-text"><%= student_course.course.description %></p>
            <hr class='divider'>
            <%= button_to 'Sign off', student_course_path(student_course), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/students/index.html.erb
<h1 class='text-center mt-5'>Students</h1>

<div class="container mt-5">
  <div class="row">
    <% students.each do |student| %>
      <div class="col-sm-4">
        <div class="card mb-5">
          <div class="card-body">
            <h5 class="card-title"><%= student.first_name + ' ' + student.last_name %></h5>
            <p><%= student.email %></p>
            <p>Course Enrollments: </p>
            <hr class='divider'>
            <%= link_to 'View Profile', student_path(student), class: 'btn btn-primary' %>
            <%= link_to 'Link', '#', class: 'btn btn-success' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<div class="card mb-5 mt-5">
  <div class="card-body">
    <h5 class="card-title"><%= student.first_name + ' ' + student.last_name %></h5>
    <p><%= student.email %></p>
    <p>Course Enrollments: </p>
    <ul>
      <% student.courses.each do |course| %>
        <li><%= course.short_name + ' ' + course.name %> </li>
      <% end %>
    </ul>
    <hr class='divider'>
    <%= link_to 'Back to Student', students_path, class: 'btn btn-primary' %>
    <%= link_to 'Link', '#', class: 'btn btn-success' %>
  </div>
</div>